# TRIKE Decaps implementation entrypoint.
rtl/bike_pkg.sv
rtl/reset_sync.sv
rtl/decoder_profile_config.sv
rtl/trike_decaps_profile_config.sv
rtl/trike_decaps_input_loader.sv
rtl/ram_bram.sv
rtl/trike_decaps_input_store.sv
rtl/trike_decaps_support_prefetch.sv
rtl/trike_decaps_syndrome_prefetch.sv
rtl/ram_i.sv
rtl/barrel_rotate.sv
rtl/edge_addr_gen.sv
rtl/tile_scheduler.sv
rtl/ram_m.sv
rtl/ram_s.sv
rtl/k_sign_update.sv
rtl/k_sign_reconstruct.sv
rtl/k_sign_overlap_scheduler.sv
rtl/ram_k_tile.sv
rtl/k_sign_selector.sv
rtl/ram_k_global.sv
rtl/ram_sign_delta.sv
rtl/ram_syndrome.sv
rtl/ram_accum.sv
rtl/ram_t.sv
rtl/msg_tc_to_signmag_sat.sv
rtl/vnu.sv
rtl/ram_decision.sv
rtl/cnu_a.sv
rtl/cnu_b.sv
rtl/msg_signmag_to_tc.sv
rtl/decoder_top.sv
rtl/trike_poly_mul_karatsuba_core.sv
rtl/trike_poly_mul_core.sv
rtl/trike_decaps_syndrome_core.sv
rtl/trike_decaps_syndrome_store_core.sv
rtl/trike_decaps_input_syndrome_core.sv
rtl/trike_decaps_input_decoder_load_core.sv
rtl/trike_fixed_support_sorter.sv
rtl/trike_decoder_load_adapter.sv
rtl/trike_decoder_error_vector.sv
rtl/trike_decoder_residual_check.sv
rtl/trike_decaps_decoder_postcheck_core.sv
rtl/sm3_compress.sv
rtl/trike_sm3_service.sv
rtl/sm3_hash_stream.sv
rtl/sm3_df_stream.sv
rtl/hmac_sm3_64byte_key_stream.sv
rtl/trike_sm3_drng_instantiate_stream.sv
rtl/trike_sm3_drng_generate_stream.sv
rtl/trike_sampler_candidate.sv
rtl/trike_fixed_weight_sampler.sv
rtl/trike_drng_weight_sampler.sv
rtl/trike_h4_error_sampler.sv
rtl/trike_error_support_store.sv
rtl/trike_h4_error_vector.sv
rtl/kem_ct_compare_select.sv
rtl/trike_ct_verify_stream.sv
rtl/trike_pseudohash512_stream.sv
rtl/trike_decaps_message_recover.sv
rtl/trike_decaps_reencrypt_verify.sv
rtl/trike_decaps_kdf.sv
rtl/trike_decaps_postprocess_core.sv
rtl/trike_decaps_pipeline_core.sv
rtl/trike_decaps_runtime_pipeline_core.sv
rtl/trike_decaps_unified_core.sv
rtl/trike_decaps_synth_top.sv
rtl/trike_decaps_runtime_synth_top.sv
